name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  PORT: 25478

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag go-file-server
    - name: Run docker image
      run: docker run -v $HOME/tmp:/var/root -p ${{ env.PORT }}:25478 go-file-server -token ${{ secrets.TOKEN }} /var/root
